---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, bluexp volume caching 
summary: 볼륨 캐싱은 원격 위치에서 쓰기 가능한 영구 볼륨을 제공합니다. BlueXP 볼륨 캐싱을 사용하여 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다. 
---
= 캐시 관리
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
캐시를 편집하고, 엑스포트 정책을 변경하고, 캐시 크기를 조정하고, 캐시를 삭제할 수 있습니다.

BlueXP 볼륨 캐싱을 사용하면 다음과 같은 목표를 달성할 수 있습니다.

* 캐시 세부 정보를 봅니다.
* 캐시에 다른 엑스포트 정책을 할당합니다.
* 볼륨 캐싱 편집 및 크기 변경 등 편집에는 다른 속성을 보고 변경할 수 있는 옵션이 있으며, 향후 릴리스에서 더 많은 속성이 편집 시 추가됩니다.
* 원래 볼륨 크기의 비율을 기준으로 기존 캐시의 크기를 조정합니다.
* 캐시를 삭제합니다.




== 캐시 세부 정보를 봅니다

각 캐싱에 대해 원래 볼륨, 작업 환경, 캐시 볼륨 등을 확인할 수 있습니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * 이동성 * > * 볼륨 캐싱 * 을 선택합니다.
+
대상 환경에서 생성된 캐시 볼륨의 목록을 볼 수 있습니다. 캐시 목록에 캐시 세부 정보가 표시됩니다.

. 목록을 필터링하려면 * Filter by+ * 옵션을 선택합니다.
. 행을 선택하고 오른쪽에서 * Actions… * 옵션을 선택합니다.
. 세부 정보 보기 및 편집 * 을 선택합니다.
. 세부 정보를 검토합니다.




== 캐시를 편집합니다

캐시에 대한 이름, 볼륨 크기 및 엑스포트 정책을 변경할 수 있습니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * 이동성 * > * 볼륨 캐싱 * 을 선택합니다.
. 행을 선택하고 오른쪽에서 * Actions… * 옵션을 선택합니다.
. 세부 정보 보기 및 편집 * 을 선택합니다.
. 기본 구성 탭에서 필요에 따라 캐시 이름과 캐시 볼륨 크기를 변경합니다.
. 필요에 따라 캐시 액세스 탭을 확장하고 다음 값을 수정합니다.
+
.. 마운트 경로입니다.
.. 기존 정책과 다른 엑스포트 정책


. SMB/CIFS 공유 세부 정보 또는 엑스포트 정책 규칙을 변경하려면 옵션을 클릭하여 BlueXP System Manager에 액세스합니다.
. 저장 * 을 선택합니다.




== 다른 캐시 엑스포트 정책을 할당합니다

캐시에 다른 엑스포트 정책을 할당할 수 있습니다.

소스 엑스포트 정책 규칙은 타겟 클러스터에 적용해야 합니다.


TIP: 캐시에 기존 엑스포트 정책을 할당할 수 있습니다. 엑스포트 정책 규칙은 변경할 수 없습니다. 엑스포트 정책을 변경해야 하는 경우 NetApp 시스템 관리자를 사용할 수 있습니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * 이동성 * > * 볼륨 캐싱 * 을 선택합니다.
. 행을 선택하고 오른쪽에서 * Actions… * 옵션을 선택합니다.
. 내보내기 정책 변경 * 을 선택합니다.
. 캐시에 할당할 엑스포트 정책을 선택합니다.
. 저장 * 을 선택합니다.




== 캐시 크기를 조정합니다

소스 볼륨의 비율에 따라 캐시 볼륨의 크기를 변경할 수 있습니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * 이동성 * > * 볼륨 캐싱 * 을 선택합니다.
. 행을 선택하고 오른쪽에서 * Actions… * 옵션을 선택합니다.
. 크기 조정 * 을 선택합니다.
. 원본 볼륨 크기의 새 비율을 입력합니다.
+
캐시 볼륨이 새 비율로 조정됩니다.

. 저장 * 을 선택합니다.




== 캐시를 삭제합니다

더 이상 캐시가 필요하지 않으면 삭제할 수 있습니다. 그러면 볼륨 캐싱 관계가 삭제되고 타겟 볼륨 캐시가 삭제됩니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * 이동성 * > * 볼륨 캐싱 * 을 선택합니다.
. 행을 선택하고 오른쪽에서 * Actions… * 옵션을 선택합니다.
. 삭제 * 를 선택합니다.
. 확인란을 선택합니다.
. 삭제 * 를 선택합니다.

