---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how bluexp volume caching works, what is volume caching, bluexp 
summary: 볼륨 캐싱은 원격 위치에서 쓰기 가능한 영구 볼륨을 제공합니다. BlueXP 볼륨 캐싱을 사용하여 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다. 
---
= BlueXP 볼륨 캐싱에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 소프트웨어의 기능인 볼륨 캐싱은 파일 배포를 간소화하고, 사용자와 컴퓨팅 리소스의 위치에 리소스를 더 가깝게 배치함으로써 WAN 대기 시간을 줄이고, WAN 대역폭 비용을 절감하는 원격 캐싱 기능입니다. 볼륨 캐싱은 원격 위치에서 쓰기 가능한 영구 볼륨을 제공합니다. BlueXP 볼륨 캐싱을 사용하여 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. 캐시 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다.

BlueXP 볼륨 캐싱을 사용하면 클라우드에 대한 캐싱 기능이 있으며, 특히 NetApp ONTAP, Cloud Volumes ONTAP 및 온-프레미스에서 작업 환경으로 사용되는 Amazon FSx를 지원합니다.

또한 지사에서 회사 데이터 세트에 액세스할 수 있습니다. 한 클러스터의 여러 컨트롤러에서 자주 액세스해야 하는 데이터인_hot data_를 제공하여 주요 애플리케이션에 제공되는 성능을 높일 수 있습니다. 또한 전 세계 여러 위치의 사용자에게 핫 데이터를 로컬로 캐싱함으로써 중앙 집중식 데이터 세트에 동시에 액세스할 수 있을 뿐 아니라 핫 데이터에 액세스할 때 받는 응답 시간도 줄여 협업을 개선할 수 있습니다.



== 캐시란 무엇입니까?

캐시는 호스트와 데이터 소스 사이에 상주하는 임시 저장 위치입니다. 캐시의 목표는 소스에서 데이터를 가져오는 것보다 더 빠르게 데이터를 제공할 수 있도록 소스 데이터의 자주 액세스하는 부분을 저장하는 것입니다. 캐시는 데이터를 두 번 이상 액세스하고 여러 호스트가 공유하는 읽기 집약적인 환경에서 가장 유용합니다. 캐시 시스템은 더 빠른 스토리지 시스템과 캐시 스토리지 공간의 호스트 근접성을 통해 데이터 소스가 있는 시스템보다 빠릅니다.



== BlueXP 볼륨 캐싱 사용의 이점

BlueXP 볼륨 캐싱은 다음과 같은 이점을 제공합니다.

* 하이브리드 클라우드 인프라의 성능 향상
* 클라우드 공급자 간에 데이터를 캐싱하여 클라우드 사일로 제거
* 저렴한 스토리지 비용
* 여러 지리적 위치에서 협업
* BlueXP에서 NetApp 관리 서비스 사용
* 변화하는 IT 환경에 신속하게 대응할 수 있습니다
* 클라우드에서 호스팅되는 온디맨드 또는 구독 기반 볼륨 캐싱




== BlueXP 볼륨 캐싱 기능

BlueXP 볼륨 캐싱은 다음과 같은 목표를 달성하기 위해 여러 NetApp 기술을 완벽하게 사용할 수 있도록 합니다.

BlueXP 볼륨 캐싱 서비스는 다음과 같은 목표를 달성하기 위해 여러 NetApp 기술을 완벽하게 사용할 수 있도록 지원합니다.

* 한 클라우드 공급자의 데이터를 다른 클라우드 공급자로 캐싱
* 캐시 엑스포트 정책을 보고 편집합니다
* 기존 캐시의 크기를 조정합니다
* 캐시를 삭제합니다




== 비용

NetApp는 BlueXP 볼륨 캐싱 서비스 사용에 대해 비용을 부과하지 않지만, 클라우드 공급자에게 데이터 수신 및 송신 요금이 있는지 확인해야 합니다.



== 라이센싱

BlueXP 볼륨 캐싱에는 특별한 ONTAP 라이센스가 필요하지 않습니다.



== BlueXP 볼륨 캐싱의 작동 방식

캐시 볼륨은 소스 볼륨으로 백업되는 인구 밀도가 낮은 볼륨입니다. 캐시 볼륨은 소스 볼륨과 동일한 클러스터 또는 다른 클러스터에 있을 수 있습니다.

캐시 볼륨은 모든 데이터가 캐시 볼륨에 있지 않아도 소스 볼륨의 데이터에 액세스할 수 있도록 합니다. 캐싱 볼륨의 데이터 스토리지는 핫 데이터(작업 데이터 또는 최근에 사용한 데이터)만 유지하여 효율적으로 관리됩니다.

BlueXP 볼륨 캐싱은 클라이언트가 요청한 데이터가 캐시 볼륨에 포함된 경우 요청을 읽습니다. 그렇지 않으면 볼륨 캐싱 서비스가 클라이언트 요청을 처리하기 전에 소스 볼륨에서 데이터를 요청하고 데이터를 저장합니다. 이후 데이터 요청은 캐시 볼륨에서 직접 제공됩니다. 첫 번째 요청 후 데이터가 더 이상 네트워크를 통해 이동하거나 오버로드된 시스템에서 제공되어서는 안 되므로 동일한 데이터에 반복적으로 액세스할 때 성능이 향상됩니다.
